source 'https://github.com/CocoaPods/Specs.git'

target 'FHSTwitterEngine', :exclusive => true do
  pod "FHSTwitterEngine", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FHSTwitterEngine", :path => "../"

  
end
